[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[log]

[ping]

[api]
  insecure = true

[providers]
  [providers.docker]

  [providers.file]
    watch = true
    filename = "dynamic_conf.toml"

